# Generated by Django 4.1.4 on 2022-12-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Доступно"), ("0", "Недоступно")],
                        default="1",
                        max_length=10,
                        verbose_name="Cтатус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Доступно"), ("0", "Недоступно")],
                        default="1",
                        max_length=100,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True,
                        help_text="Подключение элемента через URL",
                        null=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_generation.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Наследник",
                        to="menu_generation.menuitem",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент меню",
                "verbose_name_plural": "Элементы меню",
            },
        ),
    ]
