# Generated by Django 4.1.5 on 2023-01-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_generation", "0002_alter_menuitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ("menu__id", "-parent__id", "name"),
                "verbose_name": "Элемент меню",
                "verbose_name_plural": "Элементы меню",
            },
        ),
    ]
